@InventoryManagement_HostAddress = http://localhost:5054

GET {{InventoryManagement_HostAddress}}/api/Product/2
Accept: application/json

###

POST https://localhost:7004/api/Product
Content-Type: application/json

{
    "name": "Keyboard",
    "price": 1500,
    "categoryId": 1
}

###

DELETE https://localhost:7004/api/Product/1

###
POST https://localhost:7004/api/Product
Content-Type: application/json

{
    "name": "Keyboard",
    "price": 1500,
    "categoryId": 1
}

#####

GET https://localhost:7004/api/Category/1
Accept: application/json

#####

POST https://localhost:7004/api/Category
Content-Type: application/json

{
    "name": "Electronics",
    "description": "This is electronics category."
}

#####

PUT https://localhost:7004/api/Category/1
Content-Type: application/json

{
  "name": "Electronic Devices",
  "description": "Updated category description"
}

#####\

DELETE https://localhost:7004/api/Category/1